### PR TITLE
equipment is placed half a meter off the ground to make it slightly c…

### PR DESCRIPTION
**Pull request by mithray**
…learer and not digging into the ground

### CODE REVIEW

**Comment by mithray** [comment]
I thought the bow needed to be more clear so I made that the current actor. But I didn't change the actor for the swords or spears. I will do that if you like? Otherwise, all you need to change is 
```
<VisualActor>
  <Actor>items/sword.xml</Actor>
</VisualActor>
```
-> 
```
<VisualActor>
  <Actor>items/barrel_swords.xml</Actor>
</VisualActor>
```

and likewise for spears
```
<VisualActor>
  <Actor>items/sword.xml</Actor>
</VisualActor>
```
-> 
```
<VisualActor>
  <Actor>items/barrel_spears.xml</Actor>
</VisualActor>
```

**Review by mithray — COMMENTED** [review]
Sorry, I don't know why one commit message says "New pros". I meant to say "new actor files"

**Review by mithray — COMMENTED** [review]
Also, come to think of it, my latter commits likely obviated the need for changing the Position.Altitude in the first commit. I'll leave it for now as I can't test anyway. Better to see what happens first. The barrels will be floating in the air :-)

**Comment by LenaTheWolfess** [comment]
thank you,
I tried something else

**Pull request closed without merging**
